### ISSUE TITLE
Followed Instructions but install failed

### ISSUE THREAD

**Issue by thallam** [zsviczian/roam-excalidraw-issues#1]
![brave_hVAXL7iIKt](https://user-images.githubusercontent.com/1494638/111102405-c107c580-8597-11eb-85ed-1c923a6a910d.png)
Hi there, I've followed your instructions and have enabled custom components from user settings however it does not appear to have worked correctly. When I type ';;' it shows me a message that leads me to believe the custom template has not been installed. See image attafched. Any suggestions on what I can try to get this to work?

**Comment by zsviczian** [comment]
Hi Tom,
I am sorry to hear that...

- What browser are you using?
- Do you see anything under [[roam/excalidraw]]?
- Have you tried {{roam/render: ((sketching)) }}
- Do you see an error message at the top of your screen in Roam when you start the script? Click: stop this, then click Yes again, and check the top left-hand corner of roam.
- Also can you check the console log for me? When you run the script, are there any "red lines as you scroll through the log? If yes a screenshot or copy would be helpful. (You can access console.log by pressing CTRL+SHIFT+I on chrome (or F12) or developer tools in the browser menu.)
- Can you check if you can reach [roam-excalidraw.com](https://roam-excalidraw.com)? The site registration is new. I had one person who tried to access the site behind a company firewall and faced issues. It takes a few days for the domain name servers to synchronize properly.

You might find this tweet helpful:
https://twitter.com/z9sx7wox/status/1371252874123096066?s=20

**Comment by kalmir** [comment]
Hi, @zsviczian,

my issue at first was that I copied the roam/js code without checking and copying messed up the outcome (the `javascript` part became the beginning instead of `(()=>{....`.

I fixed that and your extension works – thanks! Looks great, will explore it when I have time.

But I still don't automatically get the template set (no problem for me).

Brave, no errors, roam-excalidraw.com works.

**Comment by zsviczian** [comment]
I only create the roam/template the first time the script executes... to avoid recreating it if the user decides to change it. You can always create it by opening [[roam/templates]] and adding the temple:
- Excalidraw
    - {{roam/render: ((sketching))}}
