### ISSUE TITLE
Undo propagates to Undo in roam and deletes drawing

### ISSUE THREAD

**Issue by oymehus** [zsviczian/roam-excalidraw-issues#10]
Using ctlr-z to undo does not undo in excalidraw and closes the drawing erasing it from your roam graph.

**To Reproduce**
1. Create a drawing (;;excalidraw)
2. Name drawing
2. Draw a shape.
3. Save
4. Open drawing
5. Draw another shape.
6. Press ctlr-z to undo
7. Drawing closes, and you return to page prior to page (unless you created drawing on first page after entering graph). 
8. Saved drawing is gone.

**Expected behavior**
I expect the undo command to remain local to excalidraw and not propagate to the roam-graph.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by Zak8022** [comment]
Same thing just happened to me. Lost a few minutes of inspired work. 😢  Nothing mission critical, but would love to see this corrected.

**Comment by zsviczian** [comment]
I am aware of the issue... and have a solution in place... which is clearly not enough. I will investigate further.
Hopefully, autosave now released in beta will solve the issue of losing your work.

**Comment by zsviczian** [comment]
@Zak8022 and @oymehus:
I pushed out a change to beta, which I think resolves the ctrl+z issue. Please try and let me know if this is working for you.
Here's the loader for beta:

```
{
  let s = document.createElement('script');
  s.type = 'text/javascript';
  s.src = 'https://roam-excalidraw.com/beta/loader.js';
  s.async = false;
  document.getElementsByTagName('head')[0].appendChild(s);  
}
```

**Comment by oymehus** [comment]
@zsviczian the beta seems to fix the issue.
