### ISSUE TITLE
Text overflows is not visible in the editor

### ISSUE THREAD

**Issue by JaviFuentes94** [zsviczian/roam-excalidraw-issues#14]
**Describe the bug**
When in the editor the text components have a width smaller than its content, which hides the last letters. This cannot be shown by resizing the component, as it seems like resizing the component is locked to keep the aspect ratio (with and without `Shift` clicked). 

However, the preview in Roam shows the whole content of the text component. 

**To Reproduce**
1. Go to a excalidraw editor 
2. Click on add text
3. Write a sentence
4. The sentence will be shown shorter than what you have written 

**Expected behavior**
Text components should adapt to the same size as their content when first created. 
Text components should be able to resize to a different aspect ratio.
 The drawing should look the same in the editor as in Roam.  

**Screenshots**
From the editor
![Selection_384](https://user-images.githubusercontent.com/27479569/112729632-7ab64d00-8f2d-11eb-87dd-e6c39d63709d.png)
From Roam
![Selection_385](https://user-images.githubusercontent.com/27479569/112729621-6d995e00-8f2d-11eb-8b77-1593dea69023.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 

**Additional context**
Great work! Otherwise, it works great!

**Comment by zsviczian** [comment]
Hi @JaviFuentes94!

How did you create the text element?
- in Excalidraw?
- or by nesting the text under Excalidraw?

Did you change any of the settings on  [[roam/excalidraw]] or everything is left on default?

If you double click the text in Excalidraw, then click into it and add a letter, then click somewhere on the canvas, does it fix the sizing?

I will try it on Linux, I don't have ubuntu at hand.  Have you tried other browsers or maybe on android, ios, windows, etc.?

**Comment by JaviFuentes94** [comment]
Hey @zsviczian! :)  

> How did you create the text element?

I created it on Excalidraw. 

> Did you change any of the settings on [[roam/excalidraw]] or everything is left on default?

I didn't change any of the defaults.
 
> If you double click the text in Excalidraw, then click into it and add a letter, then click somewhere on the canvas, does it fix the sizing?

Nope. It doesn't change anything. 

> I will try it on Linux, I don't have ubuntu at hand. Have you tried other browsers or maybe on android, ios, windows, etc.?

Not yet, I will report back when I do!

**Comment by zsviczian** [comment]
Hi @JaviFuentes94, I think I solved the issue with text overflows. Please ctrl+F5 on Roam to get MVP v0.31. I would appreciate a confirmation that the issue has indeed been fixed.

Thanks!

**Comment by JaviFuentes94** [comment]
Hey @zsviczian ! It seems to be working now! Thanks a lot :) 
There seems to be a small problem with the bounding boxes of text being slightly smaller than the content btw. Both in the editor and in the preview. 
![Selection_396](https://user-images.githubusercontent.com/27479569/113979577-b6aeb380-9845-11eb-9cca-a03e1cb42169.png)
This is a design detail, it doesn't affect the usability of the app, but I thought you may want to know. 
Thanks again for this awesome plugin and app!
