### ISSUE TITLE
Support for iPad with Apple Pencil

### ISSUE THREAD

**Issue by AngelPone** [zsviczian/roam-excalidraw-issues#18]
**Is your feature request related to a problem? Please describe.**
It's not very smooth use it on iPad with Apple Pencil

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zsviczian** [comment]
Yes, I am aware. Roam in the background picks up events which slows down performance.
I found that on windows, using FireFox the performance is much better. As a short term workaround, try installing FireFox on your iPad.
