### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by lamflam** [zsviczian/roam-excalidraw-issues#2]
Hi! I've been really looking forward to using this but I'm having an issue getting it installed. Here's a screenshot of the error I'm getting:
![image](https://user-images.githubusercontent.com/3680882/111194500-a7637f80-8591-11eb-976f-a787990a9ae7.png)

It seems like I don't have the `raomAlphaAPI.util` object, but I'm not sure if that's my issue or if something has changed on Roam's end.

I would appreciate any help you could offer, and happy to send more info if needed.

**Comment by zsviczian** [comment]
I am sorry to hear that you are facing issues with the install.
From the error, it seems as if the roamAlphaAPI is not up to date. When did you last update roam?
![image](https://user-images.githubusercontent.com/14358394/111197427-bdd40000-85be-11eb-936d-71dc083b0ae5.png)

**Comment by lamflam** [comment]
🤦 I thought I had updated already but I guess not because it's working now. Sorry to bother you and thanks for the response!
