### ISSUE TITLE
Error rendering component

### ISSUE THREAD

**Issue by Diprasom** [zsviczian/roam-excalidraw-issues#22]
**Describe the bug**
- When the plugin is rendered, an error message appears saying that there is an error rendering the component.
- I can still draw and insert text.

**To Reproduce**
- Steps to reproduce the behavior:
    1. Install the Plugin
    2. Type {{roam/render: ((sketching))}}
    3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/16137263/159389082-f2917d74-19f4-4882-9196-5b5ea9465c5e.png)
![image](https://user-images.githubusercontent.com/16137263/159389317-13835654-6b87-4de0-8072-95c758b9d42a.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Roam Research Desktop app
 - Version 0.9.4-3d278ad4

**Additional context**
- I don't really know what's failing to load in the first place!

**Comment by zsviczian** [comment]
I noticed this as well. You can copy the Data Block Component from here:
https://roamresearch.com/#/app/Zsolt-Blog/page/6uptQqZEV

Excalidraw is installed to [[roam/excalidraw]].

If you already have a Data Block Component section, replace the codeblock contents with the one from the link above.
![image](https://user-images.githubusercontent.com/14358394/159423418-73babf22-e24c-44ee-bc8a-d9ded6c8a216.png)

**Comment by Diprasom** [comment]
That did solve the issue. Thanks a lot for the prompt response!

P.S. I really appreciate all the work you're doing. Big fan! <3
