### ISSUE TITLE
After using export SVG to clipboard, when pasted in a block, it's text not image

### ISSUE THREAD

**Issue by kvistgaard** [zsviczian/roam-excalidraw-issues#5]

**Comment by zsviczian** [comment]
based on discussion with @kvistgaard 
@zsviczian 
When I save the image as SVG to local drive and then /upload to Roam, it looks ok to me.

@kvistgaard 
![image](https://user-images.githubusercontent.com/14358394/111764064-1ba86680-88a3-11eb-8957-c364029d4d3c.png)
Yes, but why not staying in Roam? It's not just more elegant, it's way more efficient. 
Currently it pasted the copied SVG as text. I think this can be fixed.
I think it can support many workflows. For me, it is especially important when using SVG in @dvargas92495 Presentation plug-in, at least until it starts "seeing" E4R (which the way I'll refer from now on to "Excalidraw for Roam").

**Comment by zsviczian** [comment]
Proposed solution: check clipboard when exiting editing mode. If contains SVG, then add SVG to a custom {{roam/render}} component that will render the SVG.

**Comment by zsviczian** [comment]
![2021-03-19 23-22-33](https://user-images.githubusercontent.com/14358394/111904311-9362c680-8a46-11eb-938c-946ed1b64691.gif)
