### ISSUE TITLE
CSS styling for Excalidraw

### ISSUE THREAD

**Issue by bptheodore** [zsviczian/roam-excalidraw-issues#6]
I had an initial use-case to style the Excalidraw menu bar with a "dark theme" to fit with the rest of the theme for my Roam DB.  Request would be to simplify with CSS overrides to style entire Excalidraw experience

**Comment by zsviczian** [comment]
Adding [link to tweet](https://twitter.com/bptheo/status/1371892095095480321?s=20) and images from tweet for further context

<img width="395" alt="EwnwizhVgAgylKT" src="https://user-images.githubusercontent.com/14358394/111386956-492bbf00-86ad-11eb-9af7-81d1775a888f.png">

![image](https://user-images.githubusercontent.com/14358394/111387004-5ba5f880-86ad-11eb-8588-65828cc3e949.png)

![image](https://user-images.githubusercontent.com/14358394/111387044-682a5100-86ad-11eb-8bd1-6d6cbba8e1de.png)

**Comment by zsviczian** [comment]
@bptheodore
I pushed out a change to the alpha channel. Please test.
To test the alpha channel change "dist" to "alpha" in your loader.

![image](https://user-images.githubusercontent.com/14358394/111422611-3df98300-86ef-11eb-8a63-09d6b059844c.png)

**Comment by zsviczian** [comment]
Pushing the change to production.
